Repository antimatter-dao/bas-template-bsc, pull requests merged in 2022-08, with the labels that each got.

#2 Upgrade genesis submodule to antimatter-dao
  .gitmodules
Labels: good first issue

#3 Feature/burn gas fee
  common/types.go
  consensus/consensus.go
  consensus/parlia/parlia.go
  core/state_transition.go
  eth/state_accessor.go
  eth/tracers/api.go
  internal/ethapi/api.go
Labels: enhancement

#5 Fix contract deployer not able to deploy contract due to wrong banned flag
  core/evm.go
  core/evm_test.go
Labels: hotfix

#1 build: add static link flag, update upstream ci.go
  Dockerfile
  Dockerfile.alltools
  Makefile
  build/ci.go
Labels: upstream pulling

#7 Fix unit test failure
  accounts/abi/bind/backends/simulated.go
  accounts/abi/bind/backends/simulated_test.go
  accounts/abi/bind/bind_test.go
  accounts/abi/bind/util.go
  accounts/abi/bind/util_test.go
  cmd/evm/internal/t8ntool/execution.go
  cmd/geth/accountcmd_test.go
  cmd/geth/chaincmd.go
  cmd/geth/consolecmd_test.go
  cmd/geth/dao_test.go
  cmd/geth/genesis_test.go
  cmd/geth/les_test.go
  cmd/geth/main.go
  cmd/geth/misccmd.go
  cmd/geth/usage.go
  cmd/utils/flags.go
  consensus/parlia/snapshot.go
  contracts/checkpointoracle/oracle_test.go
  core/blockchain_diff_test.go
  core/blockchain_test.go
  core/dao_test.go
  core/forkid/forkid_test.go
  core/genesis.go
  core/genesis_test.go
  core/rawdb/accessors_indexes_test.go
  core/rawdb/freezer_table_test.go
  core/vm/runtime/runtime_test.go
  docker/Dockerfile
  eth/backend.go
  eth/catalyst/api_test.go
  eth/downloader/downloader_test.go
  eth/ethconfig/config.go
  eth/ethconfig/gen_config.go
  eth/sync.go
  eth/sync_test.go
  eth/tracers/internal/tracetest/calltrace_test.go
  eth/tracers/js/tracer_test.go
  graphql/graphql_test.go
  internal/ethapi/api.go
  les/client.go
  les/peer_test.go
  les/test_helper.go
  miner/worker.go
  mobile/geth.go
  mobile/params.go
  p2p/dnsdisc/sync.go
  params/config.go
  params/dao.go
  tests/difficulty_test.go
  tests/state_test_util.go
  tests/transaction_test.go
  tests/vm_test.go
  tests/vm_test_util.go
Labels: help wanted, bug fix
