Repository antimatter-dao/bas-template-bsc, pull requests merged in 2022-09, with the labels that each got.

#8 Upstream patch: fix memory leak issue with diff protocol
  eth/handler.go
  eth/handler_diff.go
Labels: upstream pulling, bug fix

#6 CI: update github workflow config
  .github/workflows/build-devel-image.yml
  .github/workflows/build-test.yml
  .github/workflows/integration-test.yml
  .github/workflows/lint.yml
  .github/workflows/pre-release.yml
  .github/workflows/release.yml
  .github/workflows/unit-test.yml
  build/checksums.txt
Labels: enhancement

#12 fix CI on merge
  .github/workflows/build-devel-image.yml
Labels: bug fix

#17 Remove failed contract create transaction
  core/vm/evm.go
Labels: bug fix

#16 faucet add nat parameter
  cmd/faucet/faucet.go
Labels: enhancement
